apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: novacrest-customer-service
  labels:
    app: novacrest-customer-api
spec:
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: novacrest-customer-service
    weight: 100