langgraphFastapi:
  enabled: true
  name: langgraph-fastapi
  replicas: 1
  image:
    repository: quay.io/novacrest/langgraph-fastapi
    tag: 1.0.0
    pullPolicy: Always
  service:
    name: langgraph-fastapi
    port: 8000
    targetPort: 8000
  route:
    enabled: true
    name: langgraph-fastapi
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  env:
    llamaStackBaseUrl: http://llamastack-distribution-vllm-service:8321
    inferenceModel: vllm/qwen3-14b
    apiKey: fake
    customerMcpServerUrl: http://mcp-customer-service:9001/mcp
    financeMcpServerUrl: http://mcp-finance-service:9002/mcp
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 500m

chatUi:
  enabled: true
  name: simple-agent-chat-ui
  replicas: 1
  image:
    repository: quay.io/novacrest/simple-agent-chat-ui
    tag: 1.0.0
    pullPolicy: Always
  service:
    name: simple-agent-chat-ui
    port: 3000
    targetPort: 3000
  route:
    enabled: true
    name: simple-agent-chat-ui
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  env:
    chatUiPort: "3000"
    fastapiUrl: http://langgraph-fastapi:8000
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 500m
  livenessProbe:
    path: /health
    port: 3000
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    path: /health
    port: 3000
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 3
