apiVersion: v1
kind: ConfigMap
metadata:
  name: acme-finance-config
  labels:
    app: acme-finance-api
data:
  database.url: "jdbc:postgresql://postgres-fin:5432/acme_finance"
  database.username: "postgres"
  application.properties: |
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=false
    logging.level.com.acme.finance=INFO
