apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: acme-finance-service
  labels:
    app: acme-finance-api
spec:
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: acme-finance-service
    weight: 100