apiVersion: v1
kind: ConfigMap
metadata:
  name: novacrest-finance-config
  labels:
    app: novacrest-finance-api
data:
  database.url: "jdbc:postgresql://postgres-fin:5432/novacrest_finance"
  database.username: "postgres"
  application.properties: |
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=false
    logging.level.com.novacrest.finance=INFO
