{{- if .Values.mortgage.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: acme-mortgage-secret
type: Opaque
stringData:
  database.password: {{ .Values.mortgage.database.password | quote }}
{{- end }}
