{{- if .Values.postgresql.mortgage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.mortgage.service.name }}
  labels:
    app: {{ .Values.postgresql.mortgage.service.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.mortgage.service.port }}
      targetPort: postgres-mort
      protocol: TCP
      name: postgres-mort
  selector:
    app: {{ .Values.postgresql.mortgage.name }}
{{- end }}
